---
apiVersion: v1
kind: List
namespace: aocc-jupyterhub-trial
items: 
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: openscience-mage-lab
      namespace: aocc-jupyterhub-trial
    spec: 
      slug: openscience-mage-lab
      display_name: "AOCC Openscience Mage Lab"
      kubespawner_override:
        image: ghcr.io/austriandatalab/aocc_openscience_mage:sha-55e857d
        image_pull_policy: Always
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: default-notebook
      namespace: aocc-jupyterhub-trial
    spec: 
      slug: default-notebook
      display_name: "Python base notebook"
      kubespawner_override:
        image: jupyter/base-notebook

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: aocc-jupyterhub-trial
    meta.helm.sh/release-namespace: aocc-jupyterhub-trial
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-2.0.0
    component: hub
    heritage: Helm
    release: aocc-jupyterhub-trial
  name: hub
  namespace: aocc-jupyterhub-trial
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
